name: Gradix Automate
on: 
    push:
        branches: 
            - stage
jobs:
    Configure_AWS_credential:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secrets.AWS_GITHUB_ACTION_ROLE}}
                aws-region: ca-central-1
    Install_awscli:
        needs: [Configure_AWS_credential]
        runs-on: ubuntu-latest
        steps:
            - name: Install awscli
              run: pip install awscli
    List_buckets:
        needs: [Install_awscli]
        runs-on: ubuntu-latest
        steps:
            - name: Show list bucket
              run: aws s3,ls


