name: Gradix Automate
on: 
    push:
        branches: 
            - stage
jobs:
    Configure_AWS_credential:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.SECRET_KEY_ID }}
                aws-region: ca-central-1


